### ISSUE TITLE
a mistake and a question

### ISSUE THREAD

**Issue by XueXiXueXiHaHa** [taki0112/ResNet-Tensorflow#1]
Hi,taki0112:
i had read you code for learning. Great code to read and learn. 
there is a mistake in the README.md file. "--ren_n" should be "--res_n".

i look your commit,and could you explain why you chang 
      ----x_init = avg_pooling(x_init)
      ----x_init = conv(x_init, channels, kernel=1, stride=1, use_bias=use_bias, scope='conv_init')
to
      ----x_init = conv(x_init, channels*4, kernel=1, stride=2, use_bias=use_bias, scope='conv_init')
??

**Comment by taki0112** [comment]
Thank you
The reason is [original code](https://github.com/KaimingHe/resnet-1k-layers/blob/master/resnet-pre-act.lua#L83) was written `stride 2 conv`. so i fixed it
