### ISSUE TITLE
ValueError: Dimensions must be equal, but are 128 and 32 for 'network/resblock0_0/add' (op: 'Add') with input shapes: [256,32,32,1 28], [256,32,32,32].

### ISSUE THREAD

**Issue by jixiaonanzhuaizhuai** [taki0112/ResNet-Tensorflow#2]
When I set --res_n 50, the code will report a error.

def resblock(x_init, channels, is_training=True, use_bias=True, downsample=False, scope='resblock') :
    with tf.variable_scope(scope) :

        x = batch_norm(x_init, is_training, scope='batch_norm_0')
        x = relu(x)

        if downsample :
            x = conv(x, channels, kernel=3, stride=2, use_bias=use_bias, scope='conv_0')
            x_init = conv(x_init, channels, kernel=1, stride=2, use_bias=use_bias, scope='conv_init')

        else :
            x = conv(x, channels, kernel=3, stride=1, use_bias=use_bias, scope='conv_0')

        x = batch_norm(x, is_training, scope='batch_norm_1')
        x = relu(x)
        x = conv(x, channels, kernel=3, stride=1, use_bias=use_bias, scope='conv_1')

        return x + x_init

Dimensions of x and x_init are not equal.

**Comment by yang-fei** [comment]
I have the same error

**Comment by taki0112** [comment]
@jixiaonanzhuaizhuai  @yang-fei 

Sorry to delay
I fix it

Thank you
