### ISSUE TITLE
regularization not working

### ISSUE THREAD

**Issue by OsCeZrCd** [taki0112/ResNet-Tensorflow#6]
I tried this code and it seems that the resulting train/test accuracies are not changed no matter how high the regularization parameter is (in ops.py). A little digging in tensorflow documentation reveals that in order for regularization to work, you had to add the following line in build_model() in class ResNet.

self.train_loss+=tf.losses.get_regularization_loss()

**Comment by OsCeZrCd** [comment]
Actually, I found that line from stackoverflow, not tensorflow documentation:

https://stackoverflow.com/questions/44232566/add-l2-regularization-when-using-high-level-tf-layers

**Comment by taki0112** [comment]
Wow..
Thank you ! I didn't know that !
